/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Download: typeof import('./src/components/mainpage/download.vue')['default']
    ElAside: typeof import('element-plus/es')['ElAside']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElLink: typeof import('element-plus/es')['ElLink']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSkeleton: typeof import('element-plus/es')['ElSkeleton']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElText: typeof import('element-plus/es')['ElText']
    Files: typeof import('./src/components/mainpage/files.vue')['default']
    Forget: typeof import('./src/components/auth/forget.vue')['default']
    Frame: typeof import('./src/components/auth/frame.vue')['default']
    Login: typeof import('./src/components/auth/login.vue')['default']
    Loginbycode: typeof import('./src/components/auth/loginbycode.vue')['default']
    Loginbypasswd: typeof import('./src/components/auth/loginbypasswd.vue')['default']
    Logout: typeof import('./src/components/auth/logout.vue')['default']
    Register: typeof import('./src/components/auth/register.vue')['default']
    Reset: typeof import('./src/components/auth/reset.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sidebar: typeof import('./src/components/mainpage/sidebar.vue')['default']
    Topbar: typeof import('./src/components/mainpage/topbar.vue')['default']
    Upload: typeof import('./src/components/mainpage/upload.vue')['default']
    Verifiy: typeof import('./src/components/auth/verifiy.vue')['default']
  }
}
